name: Update GitHub metrics

on:
  schedule:
    - cron: "23 6 * * *"  # daily at 06:23 UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Jason-Latz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Chicago
          config_display: columns
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_lines: yes
          output: assets/metrics.svg
